#pragma once
#include <_types.h>
#include <rendering/TextureUVCoordinateSet.hpp>
#include <string>
#include <memory>
#include <math/HitResult.hpp>
#include <item/ItemInstance.hpp>
#include <util/Random.hpp>
struct TextureAtlasTextureItem;
struct TextureAtlas;
struct Mob;
struct Player;
struct Level;
struct Item{
	struct Tier
	{
		static Tier GOLD, EMERALD, IRON, STONE, WOOD;

		int32_t level, durability;
		float efficienctMultiplier;
		int32_t damageAgainstEntity;
	};
	static Item* shovel_iron;
	static Item* pickAxe_iron;
	static Item* hatchet_iron;
	static Item* flintAndSteel;
	static Item* apple;
	static Item* bow;
	static Item* arrow;
	static Item* coal;
	static Item* emerald;
	static Item* ironIngot;
	static Item* goldIngot;
	static Item* sword_iron;
	static Item* sword_wood;
	static Item* shovel_wood;
	static Item* pickAxe_wood;
	static Item* hatchet_wood;
	static Item* sword_stone;
	static Item* shovel_stone;
	static Item* pickAxe_stone;
	static Item* hatchet_stone;
	static Item* sword_emerald;
	static Item* shovel_emerald;
	static Item* pickAxe_emerald;
	static Item* hatchet_emerald;
	static Item* stick;
	static Item* bowl;
	static Item* mushroomStew;
	static Item* sword_gold;
	static Item* shovel_gold;
	static Item* pickAxe_gold;
	static Item* hatchet_gold;
	static Item* string;
	static Item* feather;
	static Item* sulphur;
	static Item* hoe_wood;
	static Item* hoe_stone;
	static Item* hoe_iron;
	static Item* hoe_emerald;
	static Item* hoe_gold;
	static Item* seeds_wheat;
	static Item* wheat;
	static Item* bread;
	static Item* helmet_cloth;
	static Item* chestplate_cloth;
	static Item* leggings_cloth;
	static Item* boots_cloth;
	static Item* helmet_chain;
	static Item* chestplate_chain;
	static Item* leggings_chain;
	static Item* boots_chain;
	static Item* helmet_iron;
	static Item* chestplate_iron;
	static Item* leggings_iron;
	static Item* boots_iron;
	static Item* helmet_diamond;
	static Item* chestplate_diamond;
	static Item* leggings_diamond;
	static Item* boots_diamond;
	static Item* helmet_gold;
	static Item* chestplate_gold;
	static Item* leggings_gold;
	static Item* boots_gold;
	static Item* flint;
	static Item* porkChop_raw;
	static Item* porkChop_cooked;
	static Item* painting;
	static Item* sign;
	static Item* door_wood;
	static Item* bucket;
	static Item* minecart;
	static Item* saddle;
	static Item* door_iron;
	static Item* redStone;
	static Item* snowBall;
	static Item* leather;
	static Item* brick;
	static Item* clay;
	static Item* reeds;
	static Item* paper;
	static Item* book;
	static Item* slimeBall;
	static Item* egg;
	static Item* compass;
	static Item* clock;
	static Item* yellowDust;
	static Item* dye_powder;
	static Item* bone;
	static Item* sugar;
	static Item* cake;
	static Item* bed;
	static Item* shears;
	static Item* melon;
	static Item* seeds_pumpkin;
	static Item* seeds_melon;
	static Item* beef_raw;
	static Item* beef_cooked;
	static Item* chicken_raw;
	static Item* chicken_cooked;
	static Item* mobPlacer;
	static Item* carrot;
	static Item* potato;
	static Item* potatoBaked;
	static Item* pumpkinPie;
	static Item* netherbrick;
	static Item* netherQuartz;
	static Item* camera;
	static Item* beetroot;
	static Item* seeds_beetroot;
	static Item* beetrootSoup;

	int32_t maxStackSize;
	std::string itemTexture;
	int32_t field_C;
	int8_t field_10, field_11, field_12, field_13;
	int32_t itemID;
	int32_t maxItemdamage;
	TextureUVCoordinateSet iconUV;
	int32_t field_34;
	int32_t field_38;
	int8_t handEquipped_;
	int8_t stackedByData;
	int8_t field_3E;
	int8_t field_3F;
	int32_t field_40;
	std::string descriptionID;

	static std::string ICON_DESCRIPTION_PREFIX;
	static Random random;
	static Item* items[];
	static std::shared_ptr<TextureAtlas> _itemTextureAtlas;
	static bool_t _D6E4C850_ItemsInitialized;

	static void initItems(std::shared_ptr<struct TextureAtlas>);
	static void teardownItems();
	static TextureAtlasTextureItem* getTextureItem(const std::string&);

	Item(int32_t id);
	HitResult getPlayerPOVHitResult(Level*, struct Player*, bool_t);
	TextureUVCoordinateSet getTextureUVCoordinateSet(const std::string&, int32_t);
	Item* setCategory(int32_t, int32_t);
	void setMaxDamage(int32_t);
	void setStackedByData(bool_t);

	virtual ~Item();
	virtual int32_t getMaxStackSize(const struct ItemInstance*);
	virtual Item* setMaxStackSize(int32_t);
	virtual bool_t canBeDepleted();
	virtual TextureUVCoordinateSet* getIcon(int32_t, int32_t, bool_t);
	virtual Item* setIcon(const std::string&, int32_t);
	virtual Item* setIcon(TextureUVCoordinateSet);
	virtual bool_t isMirroredArt();
	virtual ItemInstance* use(struct ItemInstance*, Level*, struct Player*);
	virtual bool_t useOn(struct ItemInstance*, struct Level*, int32_t, int32_t, int32_t, int32_t);
	virtual bool_t useOn(struct ItemInstance*, struct Player*, Level*, int32_t, int32_t, int32_t, int32_t, float, float, float);
	virtual int32_t getMaxUseDuration();
	virtual ItemInstance useTimeDepleted(struct ItemInstance*, Level*, struct Player*);
	virtual int32_t getUseAnimation();
	virtual void releaseUsing(struct ItemInstance*, Level*, struct Player*, int32_t);
	virtual float getDestroySpeed(struct ItemInstance*, struct Tile*);
	virtual bool_t canDestroySpecial(const struct Tile*);
	virtual int32_t getLevelDataForAuxValue(int32_t);
	virtual bool_t isStackedByData();
	virtual int32_t getMaxDamage();
	virtual int32_t getAttackDamage(struct Entity*);
	virtual void hurtEnemy(struct ItemInstance*, Mob*, Mob*);
	virtual void interactEnemy(struct ItemInstance*, Mob*, Player*);
	virtual bool_t mineBlock(struct ItemInstance*, int32_t, int32_t, int32_t, int32_t, struct Mob*);
	virtual Item* handEquipped();
	virtual bool_t isHandEquipped();
	virtual bool_t isFood();
	virtual bool_t isSeed();
	virtual bool_t isArmor();
	virtual bool_t isLiquidClipItem(int32_t);
	virtual std::string getName(const struct ItemInstance*);
	virtual std::string getDescription(void);
	virtual std::string getDescription(const struct ItemInstance*);
	virtual std::string getDescriptionId();
	virtual std::string getDescriptionId(const struct ItemInstance*);
	virtual Item* setDescriptionId(const std::string&);
	virtual bool_t isEmissive(int32_t);
	virtual int32_t getAnimationFrameFor(Mob*);

};
