#pragma once
#include <_types.h>

#define PID_LOGIN_PACKET					((int32_t)0x82)
#define PID_LOGIN_STATUS_PACKET			((int32_t)0x83)
#define PID_READY_PACKET					((int32_t)0x84)
#define PID_MESSAGE_PACKET				((int32_t)0x85)
#define PID_SET_TIME_PACKET				((int32_t)0x86)
#define PID_START_GAME_PACKET			((int32_t)0x87)
#define PID_ADD_MOB_PACKET				((int32_t)0x88)
#define PID_ADD_PLAYER_PACKET			((int32_t)0x89)
#define PID_REMOVE_PLAYER_PACKET			((int32_t)0x8a)

#define PID_ADD_ENTITY_PACKET			((int32_t)0x8c)
#define PID_REMOVE_ENTITY_PACKET			((int32_t)0x8d)
#define PID_ADD_ITEM_ENTITY_PACKET		((int32_t)0x8e)
#define PID_TAKE_ITEM_ENTITY_PACKET		((int32_t)0x8f)
#define PID_MOVE_ENTITY_PACKET			((int32_t)0x90)


#define PID_MOVE_ENTITY_POSROT_PACKET	((int32_t)0x93)
#define PID_ROTATE_HEAD_PACKET			((int32_t)0x94)
#define PID_MOVE_PLAYER_PACKET			((int32_t)0x95)
#define PID_PLACE_BLOCK_PACKET			((int32_t)0x96)
#define PID_REMOVE_BLOCK_PACKET			((int32_t)0x97)
#define PID_UPDATE_BLOCK_PACKET			((int32_t)0x98)
#define PID_ADD_PAINTING_PACKET			((int32_t)0x99)
#define PID_EXPLODE_PACKET				((int32_t)0x9A)
#define PID_LEVEL_EVENT_PACKET			((int32_t)0x9B)
#define PID_TILE_EVENT_PACKET			((int32_t)0x9C)
#define PID_ENTITY_EVENT_PACKET			((int32_t)0x9D)
#define PID_REQUEST_CHUNK_PACKET			((int32_t)0x9E)
#define PID_CHUNK_DATA_PACKET			((int32_t)0x9F)
#define PID_PLAYER_EQUIPMENT_PACKET		((int32_t)0xA0)
#define PID_PLAYER_ARMOR_EQUIPMENT_PACKET	((int32_t)0xA1)
#define PID_INTERACT_PACKET				((int32_t)0xA2)
#define PID_USE_ITEM_PACKET				((int32_t)0xA3)
#define PID_PLAYER_ACTION_PACKET			((int32_t)0xA4)

#define PID_HURT_ARMOR_PACKET			((int32_t)0xA6)
#define PID_SET_ENTITY_DATA_PACKET		((int32_t)0xA7)
#define PID_SET_ENTITY_MOTION_PACKET		((int32_t)0xA8)
#define PID_SET_ENTITY_LINK_PACKET		((int32_t)0xA9)
#define PID_SET_HEALTH_PACKET			((int32_t)0xAA)
#define PID_SET_SPAWN_POSITION_PACKET	((int32_t)0xAB)
#define PID_ANIMATE_PACKET				((int32_t)0xAC)
#define PID_RESPAWN_PACKET				((int32_t)0xAD)
#define PID_SEND_INVENTORY_PACKET		((int32_t)0xAE)
#define PID_DROP_ITEM_PACKET				((int32_t)0xAF)

#define PID_CONTAINER_OPEN_PACKET		((int32_t)0xB0)
#define PID_CONTAINER_CLOSE_PACKET		((int32_t)0xB1)
#define PID_CONTAINER_SET_SLOT_PACKET	((int32_t)0xB2)
#define PID_CONTAINER_SET_DATA_PACKET	((int32_t)0xB3)
#define PID_CONTAINER_SET_CONTENT_PACKET	((int32_t)0xB4)
#define PID_CONTAINER_ACK_PACKET			((int32_t)0xB5)
#define PID_CHAT_PACKET					((int32_t)0xB6)
#define PID_ADVENTURE_SETTINGS_PACKET	((int32_t)0xB7)
#define PID_ENTITY_DATA_PACKET			((int32_t)0xB8)
#define PID_PLAYER_INPUT_PACKET			((int32_t)0xB9)
